
error: 
`django_1       | standard_init_linux.go:228: exec user process caused: permission denied`

Grant `DBA` privilege to test user